### ISSUE TITLE
Current User permission

### ISSUE THREAD

**Issue by vikramkh** [sourcefuse/loopback4-authorization#1]
How does the application know what the current logged in users permissions are? Like should I be injecting current user in the repository, or in the controller, or in the mobile app?

**Comment by vikramkh** [comment]
I'm guessing it uses the API key in loopback4-starter? If so, is there any way to get around this?

**Comment by vikramkh** [comment]
I realized it does use the API key and I am very sorry for the unnecessary question.

**Comment by samarpan-b** [comment]
Have a look at the [`createJWT` method in login.controller](https://github.com/sourcefuse/loopback4-starter/blob/4ede6ea2fa4e39d34ce2ef9dfedb1563857dcc3c/src/modules/auth/login.controller.ts#L263) in [loopback4-starter](https://github.com/sourcefuse/loopback4-starter) package. We are fetching the user permissions and adding them to the JWT (access token) there.

Next, when this access token is received via bearer token in any API, the [`BearerTokenVerifyProvider` ](https://github.com/sourcefuse/loopback4-starter/blob/4ede6ea2fa4e39d34ce2ef9dfedb1563857dcc3c/src/modules/auth/providers/bearer-token-verify.provider.ts#L24) extracts the Auth user data containing permissions there.

The access validation happens at `Sequence.ts` [here](https://github.com/sourcefuse/loopback4-starter/blob/4ede6ea2fa4e39d34ce2ef9dfedb1563857dcc3c/src/sequence.ts#L49).

Hope this helps. I am very soon planning to post my own article on medium explaining the entire implementation here. Please bear with me until then.
