### ISSUE TITLE
How to implement email signup?

### ISSUE THREAD

**Issue by rlyttle** [sourcefuse/loopback4-authorization#23]
I see no documentation on how to implement email self-signup.

Further, it seems that DefaultUserModifyCrudRepository.create() function requires any user creating an entity to be already signed in - so this would prevent writing a custom signup controller where a non-authenticated user can call create() on the user.repository.ts.

Can some direction be provided here?

**Comment by akshatdubeysf** [comment]
Hi,

The create function in the DefaultUserModifyCrudRepository is intended to be used by other non signed in users, for new Users, you can use the default Repository.

Regarding the email self signup, you could see the implementation of a signup endpoint [here](https://github.com/sourcefuse/loopback4-microservice-catalog/blob/master/services/authentication-service/src/controllers/signup-request.controller.ts), this endpoint creates a token that you could send to the user in an email, and redirect the user to your UI from that mail. The UI would then simply validate the signup the user using this token to authenticate.
