### ISSUE TITLE
When updating to latest version, app suddenly throws TypeError

### ISSUE THREAD

**Issue by Bananenbrot1** [sourcefuse/loopback4-authorization#37]
**Describe the bug**
When upgrading to latest loopback versions. Authorization decorators are not working anymore.

**To Reproduce**
Update everything to latest version.
Start loopback

**Expected behavior**
Server starts

**Screenshots**
<img width="727" alt="Bildschirmfoto 2022-02-09 um 22 50 14" src="https://user-images.githubusercontent.com/1230544/153296073-c0280312-207c-46e6-8646-3a9f683f033b.png">

<img width="379" alt="Bildschirmfoto 2022-02-09 um 22 51 09" src="https://user-images.githubusercontent.com/1230544/153296177-dfaa9b6d-0206-4260-9fb2-e1355a3afb06.png">

**Comment by akshatdubeysf** [comment]
@Bananenbrot1 this seems to be an issue related to the @response decorators from loopback/rest, can you try removing those decorators and move the response specification to the second parameter of http method decorators (@get, @post, etc) like this - 

`
@get(path, {
responses: {
      [STATUS_CODE.OK]: <SPECIFICATION FROM RESPONSE DECORATOR>,
    }
})`

**Comment by akshatdubeysf** [comment]
Closing this as this been fixed from @loopback end as well
