### ISSUE TITLE
Throws not found for static files

### ISSUE THREAD

**Issue by akshatdubeysf** [sourcefuse/loopback4-authorization#51]
**Describe the bug**
The action provided by this package throws a not found error for static files

**To Reproduce**
1. Add the authorize action to the sequence
2. Get any static file
3. It throws not found even when the file or endpoint is in ignore list

**Expected behavior**
The endpoint should be gettable if in ignore list

**Comment by yeshamavani** [comment]
Need to test test this and then we can close this
